package com.thoughtworks.cyclerental.service;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.thoughtworks.cyclerental.dto.Customer;
import com.thoughtworks.cyclerental.dto.Cycle;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.assertEquals;

public class RentalServiceTest {

    @Test public void testSomeLibraryMethod() {
        Cycle cycle1 = new Cycle(1, "Bergamont", "Active", 100.0, 3, 50.0);;;;
        Cycle cycle2 = new Cycle(2, "Bergamont", "Active", 1000.0, 3, 500.0);;;;
        List<Cycle> cycles = Arrays.asList(cycle1, cycle2);
        Customer customer = new Customer(1, "Srujan");
        List<Customer> customers = Arrays.asList(customer);
        RentalService rentalService = new RentalService(cycles, customers);
        rentalService.rentCycle(1,1);
        rentalService.rentCycle(2,1);
        assertEquals("1",rentalService.returnCycle(1, 4));
    }

    @After
    public void tearDown() throws Exception {
    }

    @Before
    public void setUp() throws Exception {
    }
}
